#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
from bs4 import BeautifulSoup

__author__     = "Leon Schnieber"
__copyright__  = "Copyright 2018"
__credits__    = "fischertechnik GmbH"
__maintainer__ = "Leon Schnieber"
__email__      = "olaginos-buero@outlook.de"
__status__     = "Developement"


class RoboProWire():
    """
    This object is generated by an XML-String or via the attributes
    itself. Therefor objectXmlSoup has to be None so the attributes can be set
    manually. This feature is mainly used for Pseudo-Objects used on converging
    wires.
    """
    def __init__(self, wireXmlSoup=None):
        self._wireRaw = wireXmlSoup
        self._points = []
        self._begin = ""
        self._nodes = []
        self._end = ""
        self.parse()

    def parse(self):
        self._type = self._wireRaw.attrs["classname"]
        pinList = self._wireRaw.find_all("o", attrs=
            {"classname": "wxCanvasPin"})
        for pin in pinList:
            pinData = {
                "id": pin.attrs["id"],
                "name": pin.attrs["name"],
                "resovle": pin.attrs["resolveid"],
                "type": pin.attrs["pinclass"]
            }
            self._points.append(pinData)

    def getObjectList(self):
        return []
